name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
    steps:
      - name: Check commit message version format
        id: check
        run: |
          echo "status=false" >> $GITHUB_OUTPUT
          if [[ "${{ github.event.head_commit.message }}" =~ ^Bump\ to\ v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "status=true" >> $GITHUB_OUTPUT
          fi
  build:
    needs: check-commit
    if: needs.check-commit.outputs.status == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [25]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # Setup .npmrc file to publish to GitHub Packages
      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@${{ github.repository_owner }}'
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Publish package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify package was published
        run: npm info $(node -p "require('./package.json').name")
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
